FROM node:18-alpine

WORKDIR /app

COPY panel/package*.json ./
RUN npm install

COPY panel/ ./

RUN npm run build

EXPOSE 3001

# --cors разрешает все origins, -L разрешает все хосты
CMD ["npx", "serve", "-s", "dist", "-l", "3001", "--cors", "-L"]

