FROM node:18-alpine

WORKDIR /app

COPY miniapp/package*.json ./
RUN npm install

COPY miniapp/ ./

RUN npm run build

EXPOSE 3000

ENV HOST=0.0.0.0
ENV PORT=3000
CMD ["npm", "start"]

