FROM node:18-alpine

WORKDIR /app

COPY src/miniapp/package*.json ./
RUN npm install

COPY assets/ /assets/
COPY src/miniapp/ ./

RUN npm run build

EXPOSE 3000

CMD ["npx", "serve", "-s", "dist", "-l", "3000", "--cors", "-L"]
