FROM node:18-alpine

WORKDIR /app

COPY src/panel/package*.json ./
RUN npm install

COPY src/panel/ ./

RUN npm run build \
    && chown -R node:node /app

USER node

EXPOSE 3000

CMD ["npx", "serve", "-s", "dist", "-l", "3000", "--cors", "-L"]
