FROM node:18-alpine

WORKDIR /app

COPY src/panel/package*.json ./
RUN npm install

COPY src/api /api
COPY src/core /core
COPY src/panel/ ./

RUN npm run build

EXPOSE 3000

CMD ["npx", "serve", "-s", "dist", "-l", "3000", "--cors", "-L"]
